- name: Install NGINX package (DNF)
  dnf:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_distribution in ["OracleLinux", "Red Hat Enterprise Linux", "CentOS"]

- name: Install NGINX package (APT)
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: Enable and start NGINX service
  service:
    name: nginx
    enabled: yes
    state: started

- name: Allow SSH traffic through the firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - ssh
    - https

- name: Enable the firewall
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Copy default web page
  copy:
    src: default_page.html
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: 0644
