- name: Restart nginx
  service:
    name: nginx
    state: restarted
  listen: "restart stuff"

- name: Restart firewall
  service:
    name: firewalld
    state: restarted
  listen: "restart stuff"
