---

- name: Configure NGINX servers
  hosts: appservers
  become: true
  tasks:
  
  - name: Install NGINX package
    dnf:
      name: nginx
      state: present
      update_cache: yes

  - name: Enable and start NGINX service
    service:
      name: nginx
      enabled: yes
      state: started
