---
- name: Create groups and users
  hosts: databases
  become: true
  tasks:

  - name: Create groups
    group:
      gid: "{{ item.group_id}}"
      name: "{{ item.group_name}}"
      state: present
    with_items:
      - { group_name: oinstall , group_id: 54321} 
      - { group_name: dba, group_id: 54322} 
      - { group_name: oper, group_id: 54323 }

