---
- name: Configure appservers
  hosts: appservers
  become: true
  tasks:

  - name: Amend nginx.conf
    lineinfile:
      state: present
      dest: /etc/nginx/nginx.conf
      line: "# One silly a line added."
    notify: "restart stuff"

  handlers:
  - name: Restart nginx
    service:
      name: nginx
      state: restarted
    listen: "restart stuff"

  - name: Restart firewall
    service:
      name: firewalld
      state: restarted
    listen: "restart stuff"
