---
- name: Add basic packages
  hosts: all
  become: true
  tasks:

  - name: Install packages
    dnf:
      name:
        - zip
        - unzip
        - wget
      state: present
      update_cache: yes

