---
- name: Using tags
  hosts: appservers
  become: true
  tasks:
  
  - name: Install NGINX package
    tags: nginx
    dnf:
      name: nginx
      state: present
      update_cache: yes

  - name: Enable and start NGINX service
    tags: nginx
    service:
      name: nginx
      enabled: yes
      state: started

  - name: Allow SSH traffic through the firewall
    tags: firewall,fwrule
    firewalld:
      service: ssh
      permanent: yes
      state: enabled

  - name: Allow HTTPS traffic through the firewall
    tags: firewall,fwrule
    firewalld:
      service: https
      permanent: yes
      state: enabled

  - name: Enable the firewall
    tags: firewall,fwservice
    service:
      name: firewalld
      enabled: yes
      state: started
